version: '3.8'
services:
  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  api:
    build: ./docker/api
    container_name: dotnet-api
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./docker/api/appsettings.Development.json:/app/appsettings.Development.json

  ui:
    build: ./docker/ui
    container_name: react-ui
    restart: always
    depends_on:
      - api
    ports:
      - "80:80"